film user tests
dmt-100/java-filmorate pull request #2
Opened 2023-05-12 18:00 UTC by dmt-100

2023-05-13 08:03 UTC, Fleaman777 requested changes

2023-05-13 08:03 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/controller/FilmController.java
> +    FilmRepository filmRepository = new FilmRepository();
репозиторий пока немного лишний в этом спринте,
но все равно молодец, что работы с хранилищем вынес в отдельный класс,

2023-05-13 08:03 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/controller/UserController.java
> +
многовато пропусков строк, 
немного теряешься при просмотре кода, когда их больше чем нужно

2023-05-13 08:03 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/service/FilmValidator.java
> +        if (film.getName().isBlank()) {
film.getName() можно вынести в локальну. переменную, что бы постоянно не доставать это значение

2023-05-13 08:03 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/service/FilmValidator.java
> +                    maxDescriptionLength + ", film.getDescription().length: {}", film.getDescription().length());
аналагично с Description и др похожими полями

2023-05-13 08:03 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/service/UserValidator.java
> +            log.info("Проверка поля login, user.getLogin(): \"{}\"", user.getLogin());
много логов, их не должно быть больше чем самого кода)
иначе значительно ухудшается восприятие кода, 

весь лог в этом условии можно было бы заменить "логин пустой или содержит пробелы" 

и более подходящий лог левел был бы warn, т.к. в конечном счете валидация не прошла

2023-05-13 08:03 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/service/UserValidator.java
> +            log.info("Проверка поля email, user.getEmail(): {}", user.getEmail());
аналагично с пред комментарием здесь и дальше

2023-05-13 08:03 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/model/controller/FilmControllerTest.java
> +    FilmController filmController = new FilmController();
в тестах тоже хорошо придерживаться принципа инкапусляции

2023-05-13 08:03 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/model/controller/FilmControllerTest.java
> +                "а именно 20 миллионов. о Куглов, который за время «своего отсутствия», стал кандидатом Коломбани.");
описание можно было бы вынести в константу, что бы тестметод не был особо раздут

2023-05-13 08:03 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/model/controller/UserControllerTest.java
> +    void testPutUserUpdateWithWrondId() {
опечатка

2023-05-13 14:33 UTC, dmt-100 commented on src/test/java/ru/yandex/practicum/filmorate/model/controller/FilmControllerTest.java
> +    FilmController filmController = new FilmController();
Подправил, но именно в этом случае, почему надо придерживаться именно так? Имею ввиду, что будет если оставить как есть?

2023-05-14 07:38 UTC, Fleaman777 approved these changes

2023-05-14 12:32 UTC, merged