Add friends likes
dmt-100/java-filmorate pull request #4
Opened 2023-05-21 02:29 UTC by dmt-100

2023-05-22 13:04 UTC, Fleaman777 requested changes

2023-05-22 13:04 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/controller/FilmController.java
> +    private final FilmInMemoryStorage storage = new FilmInMemoryStorage();
не совсем верный автовайринг спринг компонентов, 

при таком подходе, придется больше уделять внимания этим зависимостям, 
например, при таком написании FilmInMemoryStorage storage = new FilmInMemoryStorage();;
каждый раз будет создавться новый экземпляр объекта, который будет взаимодействовать со стореджом, а если у нас сторедж как сейчас, расположен внутри программы(а не в бд), то соответственно у нас не будет единого места, где будут храниться объекты, 

если у стореджа появится еще зависимости, то нам нужно будет в каждом месте, где сторедж используется, в ручную добавлять эту зависимость и просечивать в конструтор...

если вдруг у нас поменятся реализация FilmRepository, то опять же, надо будет по всему коду вручную ее менять 

все эти вещи под капотом помагает решить спринг, если использовать @Autowire спринг бинов, 
в интернете много информации на этот счет, 
например здесь
https://habr.com/ru/articles/455794/


аналагично в др. контроллерах/сервисах..

2023-05-22 13:04 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/controller/FilmController.java
> +        return storage.getFilmById(id);
контроллер не должен напрямую обращаться к стореджу, только через соответствующий метод в сервисе, 
так мы разделим ответсвенность и каждый слой в приложении будет отвечать за свой функционал

2023-05-22 13:04 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/service/FilmService.java
> +                    .stream()
не совсем понимаю, зачем вызывать 2й раз стрим

2023-05-22 13:04 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/service/UserService.java
> +        return users;
часть этого метода хорошо можно было бы выполнить в стриме

2023-05-22 13:04 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/service/Validator.java
> +    private static UserInMemoryStorage userStorage;
валидатор можно сделать без зависимостей на стореджи, 
просто передавая подходящие аргументы в методы, 

это позволит нам иметь меньше связанность компонентов внутри приложения, а значит лучшую поддержку

2023-05-22 13:04 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/service/Validator.java
> +            field.setAccessible(true);
рефликсию лишней раз тоже лучше не использовать, 
т.к. она напрямую нарушает различные принципы ООП, 
к тому же, высока вероятность, забыть про нее, что в какой-то момент может все поломать,

этот метод checkIfAnyFieldIsNull, можно сделать другими доступными способами(например при помощи валидации через аннотации), или вообще опустить

2023-05-22 13:04 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/storage/FilmInMemoryStorage.java
> +    private final FilmRepository repository = new FilmRepository();
по сути, классы сторедж и репозиторий выполняют один и тот же функционал, их можно объеденить, 

точнее из репозитория все перенести в сторедж

2023-05-22 13:04 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/storage/UserInMemoryStorage.java
> +    private final UserRepository userRepository = new UserRepository();
аналагично комментарию в FilmInMemoryStorage

2023-05-23 00:24 UTC, dmt-100 commented on src/main/java/ru/yandex/practicum/filmorate/model/service/FilmService.java
> +                    .stream()
потому что возвращается: Optional<T> max(Comparator<? super T> comparator)
надо вызвать еще раз стрим и его уже в нужную коллекцию

2023-05-23 19:35 UTC, Fleaman777 requested changes

2023-05-23 19:35 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/controller/FilmController.java
> +        return filmStorage.getFilmById(id);
контроллер не должен напрямую обращаться к стореджу, только через соответствующий метод в сервисе

аналагично а юзер контроллере

2023-05-23 19:35 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/service/Validator.java
> +                    maxDescriptionLength + ", description.length: {}", description.length());
maxDescriptionLength так же можно добавить через плейсхолдер {}

аналагично в др логах

2023-05-24 03:04 UTC, dmt-100 commented on src/main/java/ru/yandex/practicum/filmorate/model/service/Validator.java
> +                    maxDescriptionLength + ", description.length: {}", description.length());
Такой лог только один

2023-05-24 20:42 UTC, Fleaman777 approved these changes

2023-06-12 05:14 UTC, merged