test
dmt-100/java-filmorate pull request #7
Opened 2023-09-06 12:46 UTC by dmt-100

2023-09-08 05:56 UTC, Fleaman777 requested changes

2023-09-08 05:56 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/model/controller/FilmControllerTest.java
> -public class FilmControllerTest {
что-то немного не то. 

контроллеры и сервисы удалять не надо, а пару эндпоинтов вообще нужно добавить,
так же необходимо дописать взаимодействие с БД: т.е. новые DbStorage классы, которые будут отправлять  запросы в бд, 
и ко всему этому, интеграционные тесты с применением аннотаций @SpringBootTest
@AutoConfigureTestDatabase
@RequiredArgsConstructor(onConstructor_ = @Autowired)

выглядит так, как-будто ты просто немного недопушил изменения

2023-09-08 12:37 UTC, dmt-100 commented on src/test/java/ru/yandex/practicum/filmorate/model/controller/FilmControllerTest.java
> -public class FilmControllerTest {
https://ibb.co/D5QN3SZ
Не понял что не так? 
`@SpringBootTest
@AutoConfigureTestDatabase
@RequiredArgsConstructor(onConstructor_ = @Autowired)
@Sql(scripts = "classpath:data.sql", executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
class FilmDaoStorageTest {
    private final FilmDaoStorage filmDaoStorage;
    private final MpaRatingDaoImpl mpaRatingDao;

    @Test
    void listFilms() {
        assertEquals(4, filmDaoStorage.allFilms().size());
    }

    @Test
    void getFilmById() {
        Optional<Film> filmOptional = Optional.ofNullable(filmDaoStorage.getFilmById(1));

        assertThat(filmOptional)
                .isPresent()
                .hasValueSatisfying(film ->
                        assertThat(film).hasFieldOrPropertyWithValue("filmId", 1)
                );
    }

    @Test
    void createFilm() {
        Film film = new Film();
        film.setName("film5");
        film.setDescription("description5");
        film.setReleaseDate(LocalDate.ofEpochDay(1985 - 5 - 5));
        film.setDuration(105);
        film.setRate(5);
        film.setMpa(mpaRatingDao.getMpaRatingById(1));
        filmDaoStorage.createFilm(film);
        List<Film> films = filmDaoStorage.allFilms();
        assertEquals(5, films.size());
    }

    @Test
    void updateFilm() {
        Film film = new Film();
        film.setId(1);
        film.setName("filmUpdated");
        film.setDescription("description");
        film.setReleaseDate(LocalDate.ofEpochDay(1985 - 5 - 5));
        film.setDuration(105);
        film.setRate(5);
        film.setMpa(mpaRatingDao.getMpaRatingById(1));
        filmDaoStorage.updateFilm(film);
        String value = filmDaoStorage.getFilmById(1).getName();
        assertEquals("filmUpdated", value);
    }

    @Test
    void addLikePlusGetMostPopularFilms() {
        filmDaoStorage.addLike(1, 1);
        Film popularFilm = filmDaoStorage.getMostPopularFilms(1).get(0);
        assertEquals(filmDaoStorage.getFilmById(1), popularFilm);
    }

    @Test
    void deleteLike() {
        filmDaoStorage.addLike(1, 1);
        filmDaoStorage.addLike(1, 2);
        filmDaoStorage.addLike(2, 1);
        filmDaoStorage.addLike(2, 2);
        filmDaoStorage.addLike(2, 3);
        filmDaoStorage.deleteLike(2, 1);
        filmDaoStorage.deleteLike(2, 3);
        Film popularFilm = filmDaoStorage.getMostPopularFilms(2).get(1);
        assertEquals(filmDaoStorage.getFilmById(2), popularFilm);
    }
}`

2023-09-08 12:42 UTC, dmt-100 commented on src/test/java/ru/yandex/practicum/filmorate/model/controller/FilmControllerTest.java
> -public class FilmControllerTest {
Про эндпойнты эти как понимаю? 
https://ibb.co/ZBGSYDm
Поскольку в программе появились новые сущности, то нужно обеспечить доступ к ним. Добавьте следующие эндпоинты:
1. Для получения списка всех жанров и по идентификатору.
  GET /genres 
  GET /genres/{id}

 // Пример возвращаемого значения
 {
   “id”: 1,
   “name”: “Комедия”
 }
3. Для получения жанра и рейтинга по идентификатору:
 GET /mpa
 GET /mpa/{id}

 // Пример возвращаемого значения
 {
   “id”: 1,
   “name”: “G”
 }

2023-09-08 12:47 UTC, dmt-100 commented on src/test/java/ru/yandex/practicum/filmorate/model/controller/FilmControllerTest.java
> -public class FilmControllerTest {
Про классы GenreController, GenreDaoImpl, MpaRatingController и MpaRatingDaoImpl хотелось бы понять с ними чтото не так?

2023-09-08 12:49 UTC, dmt-100 commented on src/test/java/ru/yandex/practicum/filmorate/model/controller/FilmControllerTest.java
> -public class FilmControllerTest {
Пока отправлю так, хотелось бы более подробное пояснение, как раньше=]

2023-09-09 20:42 UTC, Fleaman777 requested changes

2023-09-09 20:42 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (getFilmById(film.getId()).getId() == film.getId()
понимаю, что getFilmById здесь больше используется для валидации, 
но лучще было бы написать это проверку до условия, 
а в условии нормально сравнить айдишники, 
а то сейчас получается  мы достаем фильм по айди, а потом из этого фильма достаем айди с равниваем его, 
почему бы сразу айдишники не сравнить

2023-09-09 20:42 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
>  import java.util.List;
методы связанные с жанрами и mpa вижу, не не нашел эндпоинты, которые эти методы бы вызывали(см задание пункт Доработка бизнес-логики)

2023-09-09 20:42 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>  public class UserService implements UserStorage {
почему сервис имплементит сторедж интерфейс, 
у сервиса должен быть свой интерфейс, со своими методами и соответствующей сигнатурой

2023-09-09 20:42 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/storage/memory/FilmControllerTest.java
> +        final String DESCRIPTION_MORE_THAN_200 = "Пятеро друзей ( комик-группа «Шарло»), приезжают в город Бризуль. " + "Здесь они хотят разыскать господина Огюста Куглова, который задолжал им деньги
эту строку можно было бы вынести в константу, т.к нам в целом не важно что конкретно в ней находится, 
а если вдруг это понадобится, то можно будет просто посмотреть значение константы

2023-09-09 20:43 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/model/controller/FilmControllerTest.java
> -public class FilmControllerTest {
стало лучше, 
вижу, что добавил некоторые коммиты, собственно, которые и были нужны)

2023-09-10 09:06 UTC, dmt-100 commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
>  import java.util.List;
@GetMapping
    public List<Genre> getGenres() {
        return genreService.getGenres();
    }

    @GetMapping("/{id}")
    public Genre getGenreById(@PathVariable int id) {
        return genreService.getGenreById(id);
    }

2023-09-10 09:07 UTC, dmt-100 commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
>  import java.util.List;
@AllArgsConstructor
@RestController
@RequestMapping("/mpa")
public class MpaRatingController {

    private MpaRatingService mpaRatingService;

    @GetMapping
    public List<MpaRating> getGenres() {
        return mpaRatingService.getMpaRatings();
    }

    @GetMapping("/{id}")
    public MpaRating getGenreById(@PathVariable int id) {
        return mpaRatingService.getMpaRatingById(id);
    }
}

2023-09-10 09:08 UTC, dmt-100 commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
>  import java.util.List;
public MpaRating getMpaRatingById(int id) {
        try {
            return mpaRatingDao.getMpaRatingById(id);
        } catch (EmptyResultDataAccessException e) {
            log.warn("Ошибка запроса рейтинга.");
            throw new ResourceNotFoundException("Ошибка запроса рейтинга, проверьте корректность данных.");
        }
    }


    @Override
    public MpaRating getMpaRatingById(int id) {
        return jdbcTemplate.queryForObject(GET_RATING_BY_ID, new BeanPropertyRowMapper<>(MpaRating.class), id);
    }

2023-09-10 09:09 UTC, dmt-100 commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
>  import java.util.List;
@GetMapping
    public List<Genre> getGenres() {
        return genreService.getGenres();
    }

    @GetMapping("/{id}")
    public Genre getGenreById(@PathVariable int id) {
        return genreService.getGenreById(id);
    }

2023-09-10 09:14 UTC, dmt-100 commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
>  import java.util.List;
public Genre getGenreById(int id) {
        try {
            return genreDAO.getGenreById(id);
        } catch (EmptyResultDataAccessException e) {
            log.warn("Ошибка запроса жанра.");
            throw new ResourceNotFoundException("Ошибка запроса жанра, проверьте корректность данных.");
        }
    }


    @Override
    public Genre getGenreById(int id) {
        return jdbcTemplate.queryForObject(GET_GENRE_BY_ID, new BeanPropertyRowMapper<>(Genre.class), id);
    }

2023-09-10 09:23 UTC, dmt-100 commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
>  import java.util.List;
Так же и с mpa rating

2023-09-10 09:27 UTC, dmt-100 commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
>  import java.util.List;
см addGenreToFilm(film);

2023-09-10 09:47 UTC, dmt-100 commented on src/test/java/ru/yandex/practicum/filmorate/storage/memory/FilmControllerTest.java
> +        final String DESCRIPTION_MORE_THAN_200 = "Пятеро друзей ( комик-группа «Шарло»), приезжают в город Бризуль. " + "Здесь они хотят разыскать господина Огюста Куглова, который задолжал им деньги
@Size(max = 200)
    private String description;
немного поломал мозг, что именно не так

2023-09-10 10:47 UTC, dmt-100 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>  public class UserService implements UserStorage {
+ сойдет ли так?

2023-09-11 20:28 UTC, Fleaman777 approved these changes

2023-09-11 23:34 UTC, merged